"""``agenthicc config`` subcommand handlers."""

from __future__ import annotations

from pathlib import Path

TEMPLATE_CONFIG = """\
# agenthicc.toml — project configuration
# Generated by: agenthicc config init
# Docs: https://agenthicc.dev/docs/guides/configuration

[execution]
max_concurrent_intents = 10
max_parallel_tasks = 20
agent_pool_size = 30

[memory]
project_memory_path = ".agenthicc/memory"

[security]
default_action = "deny"

[api]
host = "127.0.0.1"
port = 8000
"""


def _do_config_show(args: object) -> None:
    from agenthicc.config import load_config  # noqa: PLC0415

    raw_overrides = getattr(args, "set_overrides", ())
    cli_overrides = (
        [item for item in raw_overrides if isinstance(item, str)]
        if isinstance(raw_overrides, (list, tuple))
        else []
    )
    raw_secret_overrides = vars(args).get("set_secret_overrides", ())
    cli_secret_overrides = (
        [item for item in raw_secret_overrides if isinstance(item, str)]
        if isinstance(raw_secret_overrides, (list, tuple))
        else []
    )
    config = load_config(
        cli_overrides=cli_overrides,
        cli_secret_overrides=cli_secret_overrides,
        config_path=vars(args).get("config_path"),
    )
    redacted = config.redacted_dict()
    print("# Effective configuration")
    for section_name, section in redacted.items():
        print(f"\n[{section_name}]")
        if not isinstance(section, dict):
            print(f"{section!r}")
            continue
        for k, v in section.items():
            print(f"{k} = {v!r}")


def _do_config_init(args: object) -> None:
    target = Path(".agenthicc") / "agenthicc.toml"
    target.parent.mkdir(parents=True, exist_ok=True)
    force = getattr(args, "force", False)
    if target.exists() and not (isinstance(force, bool) and force):
        print(f"{target} already exists. Use --force to overwrite.")
        return
    target.write_text(TEMPLATE_CONFIG)
    print(f"Created {target}")
    print("Tip — add to .gitignore:")
    print("  echo '.agenthicc/' >> .gitignore")
    print("  echo '!.agenthicc/agenthicc.toml' >> .gitignore")
