"""Configuration management commands — show, validate, profiles, and init."""

from __future__ import annotations

from pathlib import Path
from pprint import pformat

from agenthicc.cli.context import CLIContext
from agenthicc.cli.registry import command, group

_TEMPLATE = """\
# agenthicc.toml — project configuration
# Generated by: agenthicc config init
# Docs: https://agenthicc.dev/docs/guides/configuration

[execution]
max_concurrent_intents = 10
max_parallel_tasks = 20
agent_pool_size = 30

[behaviour]
verbose = false
confirm_exits = true

[memory]
project_memory_path = ".agenthicc/memory"

[security]
default_action = "deny"

[api]
host = "127.0.0.1"
port = 8000
"""


@group("config", help="Manage configuration")
def _() -> None: ...


@command("config", "show", help="Print the merged effective configuration")
def config_show(ctx: CLIContext) -> None:
    """Print the merged effective configuration including all TOML layers and --set overrides."""
    from agenthicc.config import load_config  # noqa: PLC0415

    cfg = load_config(
        cli_overrides=list(ctx.set_overrides),
        cli_secret_overrides=list(ctx.set_secret_overrides),
        config_path=ctx.config_path,
    )
    redacted = cfg.redacted_dict()
    print("# Effective configuration")
    for section_name, section in redacted.items():
        print(f"\n[{section_name}]")
        if not isinstance(section, dict):
            print(pformat(section, sort_dicts=True))
            continue
        for k, v in section.items():
            print(f"{k} = {v!r}")


@command("config", "validate", help="Validate the effective provider configuration")
def config_validate(ctx: CLIContext) -> None:
    """Validate profile selection, endpoint syntax, and required env secrets."""
    from agenthicc.config import load_config  # noqa: PLC0415

    try:
        cfg = load_config(
            cli_overrides=list(ctx.set_overrides),
            cli_secret_overrides=list(ctx.set_secret_overrides),
            config_path=ctx.config_path,
        )
        cfg.resolve_provider_profile(strict=True, requires_tools=True)
    except ValueError as exc:
        raise SystemExit(f"Configuration invalid: {exc}") from exc
    provider = cfg.execution.provider
    model = cfg.execution.effective_model()
    profile = cfg.execution.profile or "legacy execution settings"
    print(f"Configuration is valid: {profile} ({provider}/{model})")


@command("config", "profiles", help="List configured provider profiles")
def config_profiles(ctx: CLIContext) -> None:
    """List profile names and non-secret connection metadata."""
    from agenthicc.config import load_config  # noqa: PLC0415

    cfg = load_config(
        cli_overrides=list(ctx.set_overrides),
        cli_secret_overrides=list(ctx.set_secret_overrides),
        config_path=ctx.config_path,
    )
    if not cfg.providers:
        print("No provider profiles configured.")
        return
    for name in sorted(cfg.providers):
        profile = cfg.providers[name]
        model = profile.model or "<provider default>"
        endpoint = profile.base_url or "<provider default>"
        capabilities = (
            ",".join(
                f"{key}={str(value).lower()}" for key, value in sorted(profile.capabilities.items())
            )
            or "-"
        )
        print(f"{name}\t{profile.provider}\t{model}\t{endpoint}\t{capabilities}")


@command("config", "init", help="Create a template agenthicc.toml in .agenthicc/")
def config_init(ctx: CLIContext, force: bool = False) -> None:
    """Create a template agenthicc.toml. Use --force to overwrite an existing file."""
    target = Path(".agenthicc") / "agenthicc.toml"
    target.parent.mkdir(parents=True, exist_ok=True)
    if target.exists() and not force:
        print(f"{target} already exists. Use --force to overwrite.")
        return
    target.write_text(_TEMPLATE)
    print(f"Created {target}")
    print("Tip — add to .gitignore:")
    print("  echo '.agenthicc/' >> .gitignore")
    print("  echo '!.agenthicc/agenthicc.toml' >> .gitignore")
