"""Configuration management commands — config show, config init."""

from __future__ import annotations

from pathlib import Path

from agenthicc.cli.context import CLIContext
from agenthicc.cli.registry import command, group

_TEMPLATE = """\
# agenthicc.toml — project configuration
# Generated by: agenthicc config init
# Docs: https://agenthicc.dev/docs/guides/configuration

[execution]
max_concurrent_intents = 10
max_parallel_tasks = 20
agent_pool_size = 30

[behaviour]
verbose = false
confirm_exits = true

[memory]
project_memory_path = ".agenthicc/memory"

[security]
default_action = "deny"

[api]
host = "127.0.0.1"
port = 8000
"""


@group("config", help="Manage configuration")
def _() -> None: ...


@command("config", "show", help="Print the merged effective configuration")
def config_show(ctx: CLIContext) -> None:
    """Print the merged effective configuration including all TOML layers and --set overrides."""
    from agenthicc.config import load_config  # noqa: PLC0415

    cfg = load_config(cli_overrides=list(ctx.set_overrides))
    print("# Effective configuration")
    for section_name in ["execution", "behaviour", "memory", "security", "api", "tools", "plugins"]:
        section = getattr(cfg, section_name, None)
        if section is None:
            continue
        print(f"\n[{section_name}]")
        for k, v in vars(section).items():
            print(f"{k} = {v!r}")


@command("config", "init", help="Create a template agenthicc.toml in .agenthicc/")
def config_init(ctx: CLIContext, force: bool = False) -> None:
    """Create a template agenthicc.toml. Use --force to overwrite an existing file."""
    target = Path(".agenthicc") / "agenthicc.toml"
    target.parent.mkdir(parents=True, exist_ok=True)
    if target.exists() and not force:
        print(f"{target} already exists. Use --force to overwrite.")
        return
    target.write_text(_TEMPLATE)
    print(f"Created {target}")
    print("Tip — add to .gitignore:")
    print("  echo '.agenthicc/' >> .gitignore")
    print("  echo '!.agenthicc/agenthicc.toml' >> .gitignore")
