"""Entry point for ``python -m agenthicc`` and the ``agenthicc`` command."""

from __future__ import annotations

import argparse
import asyncio
import json
import os
import sys
import time
import uuid
from pathlib import Path
from typing import Any


# ── session index helpers ────────────────────────────────────────────────────

_SESSIONS_DIR  = Path(".agenthicc/sessions")
_SESSION_INDEX = Path(".agenthicc/sessions.json")


def _load_session_index() -> dict:
    if _SESSION_INDEX.exists():
        try:
            return json.loads(_SESSION_INDEX.read_text())
        except Exception:
            return {}
    return {}


def _save_session_index(index: dict) -> None:
    _SESSION_INDEX.parent.mkdir(parents=True, exist_ok=True)
    _SESSION_INDEX.write_text(json.dumps(index, indent=2))


def _register_session(session_id: str) -> None:
    index = _load_session_index()
    index[session_id] = {
        "cwd": os.getcwd(),
        "created_at": time.time(),
        "last_used": time.time(),
        "log_path": str(_SESSIONS_DIR / f"{session_id}.jsonl"),
    }
    _save_session_index(index)


def _touch_session(session_id: str) -> None:
    index = _load_session_index()
    if session_id in index:
        index[session_id]["last_used"] = time.time()
        _save_session_index(index)


def _find_latest_session_for_cwd() -> str | None:
    index = _load_session_index()
    cwd = os.getcwd()
    candidates = [
        (data.get("last_used", 0), sid)
        for sid, data in index.items()
        if data.get("cwd") == cwd
    ]
    return max(candidates)[1] if candidates else None


def _get_session_log_path(session_id: str) -> Path | None:
    index = _load_session_index()
    entry = index.get(session_id)
    if entry:
        return Path(entry["log_path"])
    return None


# ── argument parsing ──────────────────────────────────────────────────────────

def _parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        prog="agenthicc",
        description="Agenthicc — state-driven agent OS for autonomous software engineering",
    )
    parser.add_argument("--headless", action="store_true",
                        help="Run without the TUI; emit JSON-lines to stdout.")
    parser.add_argument("--config", metavar="PATH", default=None,
                        help="Path to agenthicc.toml.")
    parser.add_argument("--version", action="version", version="agenthicc 0.1.0")
    parser.add_argument("--continue", dest="continue_session", action="store_true",
                        help="Continue the most recent session for this directory.")
    parser.add_argument("--resume", metavar="ID", default=None,
                        help="Resume the session with the given ID.")

    parser.add_argument(
        "--set",
        metavar="KEY=VALUE",
        action="append",
        default=[],
        dest="set_overrides",
        help="Override a config key (section.key=value). Can be repeated.",
    )

    subparsers = parser.add_subparsers(dest="command")
    subparsers.add_parser("login",   help="Authenticate with agenthicc.ai")
    subparsers.add_parser("logout",  help="Log out and revoke tokens")
    subparsers.add_parser("whoami",  help="Show current authenticated user")
    subparsers.add_parser("sessions", help="List saved sessions")

    config_parser = subparsers.add_parser("config", help="Manage configuration")
    config_sub = config_parser.add_subparsers(dest="config_command")
    config_sub.add_parser("show", help="Print the merged effective configuration")
    config_init_p = config_sub.add_parser("init", help="Create a template agenthicc.toml")
    config_init_p.add_argument("--force", action="store_true", help="Overwrite existing config")

    return parser.parse_args()


# ── config subcommand ─────────────────────────────────────────────────────────

TEMPLATE_CONFIG = """\
# agenthicc.toml — project configuration
# Generated by: agenthicc config init
# Docs: https://agenthicc.dev/docs/guides/configuration

[execution]
max_concurrent_intents = 10
max_parallel_tasks = 20
agent_pool_size = 30

[memory]
project_memory_path = ".agenthicc/memory"

[security]
default_action = "deny"

[api]
host = "127.0.0.1"
port = 8000
"""


def _do_config_show(args) -> None:
    from agenthicc.config import load_config  # noqa: PLC0415
    cli_overrides = getattr(args, "set_overrides", [])
    config = load_config(cli_overrides=cli_overrides)
    print("# Effective configuration")
    for section_name in ["execution", "memory", "security", "api", "tools"]:
        section = getattr(config, section_name, None)
        if section is None:
            continue
        print(f"\n[{section_name}]")
        for k, v in vars(section).items():
            print(f"{k} = {v!r}")


def _do_config_init(args) -> None:
    target = Path(".agenthicc") / "agenthicc.toml"
    target.parent.mkdir(parents=True, exist_ok=True)
    if target.exists() and not getattr(args, "force", False):
        print(f"{target} already exists. Use --force to overwrite.")
        return
    target.write_text(TEMPLATE_CONFIG)
    print(f"Created {target}")
    print("Tip — add to .gitignore:")
    print("  echo '.agenthicc/' >> .gitignore")
    print("  echo '!.agenthicc/agenthicc.toml' >> .gitignore")


# ── auth subcommands ──────────────────────────────────────────────────────────

async def _do_login() -> None:
    from agenthicc.auth import AuthClient
    client = AuthClient()
    bundle = await client.login()
    print(f"Logged in as {bundle.email}  [plan: {bundle.plan}]")


async def _do_logout() -> None:
    from agenthicc.auth import AuthClient
    await AuthClient().logout()
    print("Logged out.")


def _do_whoami() -> None:
    from agenthicc.auth import AuthClient
    bundle = AuthClient().current_bundle()
    if bundle is None:
        print("Not logged in. Run: agenthicc login")
    else:
        exp = time.strftime("%Y-%m-%d %H:%M", time.localtime(bundle.expires_at))
        print(f"{bundle.email}  plan={bundle.plan}  token_expires={exp}")


def _do_sessions() -> None:
    index = _load_session_index()
    if not index:
        print("No saved sessions.")
        return
    cwd = os.getcwd()
    for sid, data in sorted(index.items(), key=lambda x: x[1].get("last_used", 0), reverse=True):
        marker = " *" if data.get("cwd") == cwd else ""
        last = time.strftime("%Y-%m-%d %H:%M", time.localtime(data.get("last_used", 0)))
        print(f"  {sid[:12]}  {last}  {data.get('cwd', '')} {marker}")


# ── headless mode ─────────────────────────────────────────────────────────────

async def _run_headless() -> None:
    from agenthicc.kernel import AppState, Event, EventProcessor, SecurityPolicy, SystemSettings

    state = AppState.create(settings=SystemSettings(), policy=SecurityPolicy())
    processor = EventProcessor(initial_state=state, persist=False)
    sub = processor.subscribe()
    proc_task = asyncio.create_task(processor.run())
    print(json.dumps({"status": "ready", "mode": "headless"}), flush=True)
    try:
        while True:
            line = await asyncio.get_event_loop().run_in_executor(None, sys.stdin.readline)
            if not line:
                break
            text = line.strip()
            if not text:
                continue
            intent_id = uuid.uuid4().hex
            await processor.emit(Event.create("IntentCreated", {"intent_id": intent_id, "raw_text": text}))
            try:
                snap = await asyncio.wait_for(sub.get(), timeout=2.0)
                intent = snap.intents.get(intent_id)
                print(json.dumps({"event_type": "IntentCreated", "intent_id": intent_id,
                                  "status": intent.status.value if intent else "pending"}), flush=True)
            except asyncio.TimeoutError:
                print(json.dumps({"event_type": "Error", "message": "timeout"}), flush=True)
    finally:
        proc_task.cancel()
        await asyncio.gather(proc_task, return_exceptions=True)


# ── TUI session ───────────────────────────────────────────────────────────────

def _build_agent_runner(llm_cfg: Any, transcript: Any = None) -> Any:
    """Build a lauren-ai AgentRunnerBase wired to a SignalBus for tool-call tracking."""
    if llm_cfg is None:
        return None
    from lauren_ai._agents._runner import AgentRunnerBase  # noqa: PLC0415
    from lauren_ai._module import _build_transport  # noqa: PLC0415
    from lauren_ai._signals import SignalBus  # noqa: PLC0415

    bus = SignalBus()

    if transcript is not None:
        # Capture the current agent_id at signal time via closure over a mutable cell
        _current_agent: list[str] = ["system"]

        @bus.on_any
        async def _route(sig: Any) -> None:
            sig_type = type(sig).__name__
            if sig_type == "ToolCallStarted":
                transcript.add_tool_call(
                    agent_id=_current_agent[0],
                    tool_use_id=getattr(sig, "tool_use_id", ""),
                    name=getattr(sig, "tool_name", ""),
                    args=dict(getattr(sig, "input", {}) or {}),
                )
            elif sig_type == "ToolCallComplete":
                transcript.finish_tool_call(
                    tool_use_id=getattr(sig, "tool_use_id", ""),
                    success=bool(getattr(sig, "success", True)),
                    duration_ms=getattr(sig, "duration_ms", None),
                    error=getattr(sig, "error", None),
                )

        # Expose the agent cell so _run_agent_turn can set it
        bus._current_agent_cell = _current_agent  # type: ignore[attr-defined]

    transport = _build_transport(llm_cfg)
    return AgentRunnerBase(transport=transport, signals=bus)


async def _run_agent_turn(
    text: str,
    runner: Any,
    transcript: Any,
    renderer: Any,
    processor: Any,
    session_memory: Any = None,
    max_agent_turns: int = 200,
) -> None:
    """Run one agent turn: call LLM, stream response into transcript, show Rich spinner."""
    import re as _re  # noqa: PLC0415
    from lauren_ai._agents import agent as agent_decorator, use_tools  # noqa: PLC0415
    from lauren_ai.testing import _build_runner_for_agent  # noqa: PLC0415
    from agenthicc.kernel import Event  # noqa: PLC0415

    if runner is None:
        transcript.append_turn("system", "system", time.monotonic())
        transcript.append_line("system", "⚠ No LLM configured. Set ANTHROPIC_API_KEY or OPENAI_API_KEY.")
        return

    # ── resolve model_id FIRST (fixes UnboundLocalError) ──────────────────
    model_id = (
        runner._transport._config.model
        if hasattr(runner._transport, "_config")
        else "unknown"
    )
    model_short = model_id.split("/")[-1]

    # ── kernel event ──────────────────────────────────────────────────────
    intent_id = uuid.uuid4().hex
    await processor.emit(Event.create("IntentCreated", {"intent_id": intent_id, "raw_text": text}))

    agent_id = f"agent-{intent_id[:8]}"
    transcript.append_turn(agent_id, f"assistant ({model_short})", time.monotonic())

    # ── let signal bridge know the current agent ──────────────────────────
    cell = getattr(getattr(runner, "_signals", None), "_current_agent_cell", None)
    if cell is not None:
        cell[0] = agent_id

    # ── status bar + Rich Live spinner ────────────────────────────────────
    renderer._status.active = True
    renderer._status.intent_started_at = time.monotonic()
    renderer._status.input_tokens = 0
    renderer._status.output_tokens = 0

    # Wire ModelCallComplete signal → live token count updates in the spinner.
    # Fires once per LLM turn so counts accumulate in real-time during multi-turn runs.
    _signals = getattr(runner, "_signals", None)

    # Keyed by tool_use_id: (relative_path, original_content) captured before the call.
    _file_snapshots: dict[str, tuple[str, str]] = {}
    # File-editing tool names that warrant a unified diff in the transcript.
    _FILE_EDIT_TOOLS = {"write_file", "patch_file", "append_file"}

    from agenthicc.tui.render_loop import RenderLoop as _RL  # noqa: PLC0415
    from agenthicc.tui.frame_composer import FrameComposer as _FC  # noqa: PLC0415
    from agenthicc.tui.terminal import FakeTerminal as _FakeTerm  # noqa: PLC0415
    _rl_terminal = getattr(renderer, "_terminal", None) or _FakeTerm()
    _rl = _RL(_rl_terminal, _FC())
    renderer._status.partial_text = ""
    _any_tool_calls: list[bool] = [False]

    if _signals is not None:
        from lauren_ai._signals import ModelCallComplete as _MCC  # noqa: PLC0415
        from lauren_ai._signals import ToolCallStarted as _TCS, ToolCallComplete as _TCC  # noqa: PLC0415

        # Guard: the runner's SignalBus accumulates handlers across turns because
        # _run_agent_turn() re-registers on every call.  _handler_active is set to
        # False in the finally block so only the CURRENT turn's closures fire.
        _handler_active = [True]

        @_signals.on(_MCC)
        async def _on_model_complete(sig: Any) -> None:
            if not _handler_active[0]:
                return
            usage = getattr(sig, "usage", None)
            if usage:
                renderer._status.input_tokens += getattr(usage, "input_tokens", 0)
                renderer._status.output_tokens += getattr(usage, "output_tokens", 0)
            renderer._status.session_cost_usd += getattr(sig, "cost_usd", 0.0) or 0.0

        @_signals.on(_TCS)
        async def _on_tool_started(sig: Any) -> None:
            if not _handler_active[0]:
                return
            args = dict(getattr(sig, "input", {}) or {})
            tool_name = getattr(sig, "tool_name", "")
            tid = getattr(sig, "tool_use_id", "")
            # Format args as Claude Code style: first value only if single, else key=val pairs
            items = list(args.items())
            if len(items) == 1:
                args_str = repr(items[0][1])[:50]
            elif items:
                args_str = ", ".join(f"{k}={repr(v)[:25]}" for k, v in items[:3])
                if len(items) > 3:
                    args_str += ", …"
            else:
                args_str = ""
            _any_tool_calls[0] = True
            _rl.tick(transcript, renderer._status, None)
            # Snapshot file content before write/patch so we can produce a diff later.
            if tool_name in _FILE_EDIT_TOOLS:
                rel_path = args.get("path", "")
                if rel_path:
                    full = os.path.join(os.getcwd(), rel_path) if not os.path.isabs(rel_path) else rel_path
                    try:
                        original = await asyncio.to_thread(
                            lambda p=full: open(p).read() if os.path.exists(p) else ""
                        )
                        _file_snapshots[tid] = (rel_path, original)
                    except Exception:
                        pass

        @_signals.on(_TCC)
        async def _on_tool_complete(sig: Any) -> None:
            if not _handler_active[0]:
                return
            import difflib as _dl  # noqa: PLC0415
            tid = getattr(sig, "tool_use_id", "")
            success = bool(getattr(sig, "success", True))
            duration_ms = getattr(sig, "duration_ms", 0.0) or 0.0
            error = getattr(sig, "error", None) if not success else None
            diff: str | None = None
            # Generate unified diff for file-editing tools and store as transcript output.
            if tid in _file_snapshots:
                rel_path, original = _file_snapshots.pop(tid)
                full = os.path.join(os.getcwd(), rel_path) if not os.path.isabs(rel_path) else rel_path
                try:
                    new_content = await asyncio.to_thread(
                        lambda p=full: open(p).read() if os.path.exists(p) else ""
                    )
                    # Use splitlines() WITHOUT keepends + lineterm="" + "\n".join so
                    # the ---/+++/@@ control lines each land on their own line.  Using
                    # keepends=True with lineterm="" concatenates the control headers
                    # into one giant line ("--- a/f+++ b/f@@ …") which then wraps and
                    # corrupts the scroll-region layout.
                    diff = "\n".join(_dl.unified_diff(
                        original.splitlines(),
                        new_content.splitlines(),
                        fromfile=f"a/{rel_path}",
                        tofile=f"b/{rel_path}",
                        lineterm="",
                    ))
                    if diff:
                        transcript.finish_tool_call(tool_use_id=tid, output=diff)
                except Exception:
                    pass
            _rl.tick(transcript, renderer._status, None)

    # ── @mention injection ────────────────────────────────────────────
    from agenthicc.mentions.injector import build_context_prefix, InjectionConfig  # noqa: PLC0415
    from agenthicc.tui.transcript import MentionChip  # noqa: PLC0415
    _exec_cfg = getattr(renderer, "_exec_cfg", None)
    _mention_cfg = InjectionConfig(
        mention_token_budget=getattr(_exec_cfg, "mention_token_budget", 32_000),
        max_file_chars=getattr(_exec_cfg, "mention_max_file_chars", 16_000),
        max_glob_files=getattr(_exec_cfg, "mention_max_glob_files", 20),
        cwd=Path(os.getcwd()),
    )
    _mention_cache_ref = getattr(renderer, "_mention_cache", None)
    _mention_prefix, _injected = await build_context_prefix(
        text,
        cwd=_mention_cfg.cwd,
        cfg=_mention_cfg,
        cache=_mention_cache_ref,
        current_turn=renderer._status.completed_agents,
    )
    _agent_text = _mention_prefix + text if _mention_prefix else text

    # Add @mention chips to transcript
    if _injected:
        from agenthicc.mentions.parser import MentionKind as _MK  # noqa: PLC0415
        for r in _injected:
            if r.mention.kind == _MK.FILE:
                chip = MentionChip(raw=r.mention.raw, kind="file",
                                   display_size=f"{r.chars_used/1024:.1f} KB", ok=r.ok, error=r.error)
            elif r.mention.kind == _MK.DIRECTORY:
                chip = MentionChip(raw=r.mention.raw, kind="dir", display_size="", ok=r.ok)
            elif r.mention.kind == _MK.GLOB:
                count = r.block.count("<file ")
                chip = MentionChip(raw=r.mention.raw, kind="glob",
                                   display_size=f"→ {count} file{'s' if count!=1 else ''}", ok=r.ok)
            elif r.mention.kind == _MK.URL:
                chip = MentionChip(raw=r.mention.raw, kind="url",
                                   display_size=f"{r.chars_used:,} chars" if r.ok else "", ok=r.ok)
            else:
                chip = MentionChip(raw=r.mention.raw, kind="unresolved",
                                   display_size="", ok=False, error="not found")
            transcript.add_mention_chips(agent_id, [chip])
            if r.block and r.ok:
                transcript.set_mention_content(agent_id, r.mention.raw, r.block)

    # ── skills auto-triggering ────────────────────────────────────────
    from agenthicc.skills.runner import find_matching_skills, process_skill_body  # noqa: PLC0415
    _matched_skills = find_matching_skills(text, getattr(renderer, "_skills", {}) or {})
    _skill_suffix = ""
    if _matched_skills:
        _addenda = "\n\n".join(
            f"## Skill: {s.name}\n{process_skill_body(s, args=[], cwd=Path(os.getcwd()))}"
            for s in _matched_skills
        )
        _skill_suffix = f"\n\n---\n\n{_addenda}"

    # Build the agent class with tools so it can actually DO things
    from agenthicc.plugins.registry import build_registry  # noqa: PLC0415
    _mcp_tools = []
    _mcp_reg = getattr(renderer, "_mcp_registry", None)
    if _mcp_reg is not None:
        _mcp_tools = _mcp_reg.all_tools()
    _registry = build_registry(
        agent_name=getattr(renderer, "_active_agent", None) or "default",
        project_plugin_tools=(getattr(renderer, "_project_plugin_tools", None) or []) + _mcp_tools,
    )
    _tool_description = _registry.describe()

    @agent_decorator(
        model=model_id,
        system=(
            "You are a capable AI assistant with access to filesystem, shell, "
            "and git tools. Use them directly to complete tasks. "
            "Give concise responses. Show command output when relevant. "
            "Never invent file contents — always read them first."
            + (_skill_suffix if _skill_suffix else "")
            + (f"\n\n{_tool_description}" if _tool_description else "")
        ),
    )
    @use_tools(*_registry.tools)
    class _AgenthiccAgent: ...

    # Use _build_runner_for_agent so tools are resolved correctly from @use_tools metadata
    _agent_instance = _AgenthiccAgent()
    _active_runner = _build_runner_for_agent(
        _agent_instance,
        runner._transport,
        signals=getattr(runner, "_signals", None),
    )

    # Per-turn text accumulation (run_stream yields chunks across all turns)
    _current_turn: list[str] = []
    _all_turn_texts: list[str] = []     # one entry per LLM turn that produced text
    content = ""

    try:
        from lauren_ai._config import AgentConfig as _AgentConfig  # noqa: PLC0415
        _cfg = _AgentConfig(
            max_turns=max_agent_turns,
            parallel_tool_calls=True,
        )
        _stream = await _active_runner.run_stream(
            _agent_instance,
            _agent_text,
            memory=session_memory,
            config_override=_cfg,
        )
        async for _chunk in _stream:
            # Accumulate text delta into the current turn buffer.
            if _chunk.delta:
                _current_turn.append(_chunk.delta)
                renderer._status.partial_text = (getattr(renderer._status, "partial_text", "") or "") + _chunk.delta
                _rl.tick(transcript, renderer._status, None)

            # A chunk with stop_reason marks the end of one LLM turn.
            if _chunk.stop_reason is not None:
                _turn_text = "".join(_current_turn).strip()
                if _turn_text:
                    _all_turn_texts.append(_turn_text)
                    # Add text to transcript NOW — before _stream_loop() executes
                    # tools for this turn.  ToolCallStarted/Complete signals fire
                    # after this yield, so the transcript order becomes:
                    #   turn-1 text → turn-1 tools → turn-2 text → turn-2 tools …
                    from agenthicc.tui.app import InlineRenderer as _IR  # noqa: PLC0415
                    transcript.append_line(agent_id, _IR._MD_SENTINEL + _turn_text)
                renderer._status.partial_text = ""
                _rl.force_commit(transcript, renderer._status, None)
                _current_turn = []

        # Build final content from the last turn (replaces response.content).
        content = _all_turn_texts[-1] if _all_turn_texts else ""
        # Strip any residual XML that slipped through
        content = _re.sub(r"<tool_call>.*?</tool_call>", "", content, flags=_re.DOTALL)
        content = _re.sub(r"<[^>]+>", "", content).strip()
        # If tools ran but the final turn produced no prose, that's fine — skip it.
        if not content and not _any_tool_calls[0]:
            content = "(no response)"

    except (asyncio.CancelledError, KeyboardInterrupt):
        # Ctrl+C pressed while the agent was running.  Clean exit — nothing to
        # append to the transcript; the input loop will resume normally.
        content = ""
        _all_turn_texts = []
    except Exception as exc:
        content = f"⚠ Error: {exc}"
        _all_turn_texts = []
    finally:
        # Deactivate this turn's signal handlers so they become no-ops for future
        # turns (the runner's SignalBus accumulates handlers indefinitely).
        if _signals is not None:
            _handler_active[0] = False
        renderer._status.active = False
        renderer._status.completed_agents += 1
        renderer._status.partial_text = ""
        # Erase the bottom block so _print_status() + read_line_with_mention()
        # in the outer loop can draw the idle input bar cleanly.
        _rl_terminal = getattr(renderer, "_terminal", None)
        if _rl_terminal is not None:
            _rl_terminal.clear_bottom()

    from agenthicc.tui.app import InlineRenderer  # noqa: PLC0415

    # Turn texts were added to the transcript at each stop_reason (inside the
    # stream loop above) so they interleave correctly with tool call signals.
    # The only case we still need to append here is the synthetic "(no response)".
    if content == "(no response)":
        transcript.append_line(agent_id, InlineRenderer._MD_SENTINEL + content)

    # Advance _printed_count so _flush_new_lines() (called in the outer loop)
    # does not re-print content already committed to scrollback by the RenderLoop.
    renderer._printed_count = len(transcript.render())

    await processor.emit(
        Event.create("IntentStatusChanged", {"intent_id": intent_id, "status": "complete"})
    )


async def _run_tui_session(resume_id: str | None = None, cli_overrides: list[str] | None = None) -> None:
    from agenthicc.kernel import AppState, EventProcessor, SecurityPolicy, SystemSettings
    from agenthicc.kernel.reducer import root_reducer
    from agenthicc.kernel.processor import restore_from_log
    from agenthicc.tui.transcript import TranscriptModel
    from agenthicc.tui.events import TUIEventAdapter
    from agenthicc.tui.app import InlineRenderer
    from agenthicc.config import load_config, build_llm_config
    from agenthicc.conversation_store import ConversationStore  # noqa: PLC0415

    session_id = resume_id or uuid.uuid4().hex
    _SESSIONS_DIR.mkdir(parents=True, exist_ok=True)
    log_path = str(_SESSIONS_DIR / f"{session_id}.jsonl")

    settings = SystemSettings(
        event_log_path=log_path,
        snapshot_path=".agenthicc/snapshot.json",
    )
    state = AppState.create(settings=settings, policy=SecurityPolicy())

    # Restore from log when resuming
    if resume_id:
        log_file = _get_session_log_path(resume_id)
        if log_file and log_file.exists():
            state = await restore_from_log(str(log_file), state, root_reducer)
        _touch_session(resume_id)
    else:
        _register_session(session_id)

    processor = EventProcessor(initial_state=state, persist=True)
    model = TranscriptModel()
    adapter = TUIEventAdapter(model)
    adapter.subscribe_to(processor)

    # Load config and build LLM transport for agent runs
    cfg = load_config(cli_overrides=cli_overrides or [])
    try:
        llm_cfg = build_llm_config(cfg.execution)
    except ValueError as exc:
        from rich.console import Console  # noqa: PLC0415
        Console().print(f"[red]LLM config error: {exc}[/red]\n"
                        "[dim]Set ANTHROPIC_API_KEY or OPENAI_API_KEY env var, or use --set execution.provider=...[/dim]",
                        markup=True)
        llm_cfg = None

    renderer = InlineRenderer(
        model, adapter,
        base_path=os.getcwd(),
        history_file=".agenthicc/history",
    )
    renderer._processor = processor
    renderer._status.session_id = (
        f"{cfg.execution.provider}/{cfg.execution.effective_model()}"
    )
    renderer._status.resume_id = session_id
    renderer._loaded_config = cfg   # used by ConfigurationMenu

    renderer._active_agent = "default"
    renderer._exec_cfg = cfg.execution  # expose to _run_agent_turn for @mention config

    # ── skills discovery ──────────────────────────────────────────────
    from agenthicc.skills.loader import discover_skills as _discover_skills
    _skills = _discover_skills(
        project_dir=Path(".agenthicc"),
        user_dir=Path.home() / ".agenthicc",
    )
    renderer._skills = _skills

    # ── tool plugin discovery ─────────────────────────────────────────────
    from agenthicc.plugins.discovery import discover_project_tools, warn_conflicts  # noqa: PLC0415
    _project_plugins = discover_project_tools(
        project_dir=Path(".agenthicc"),
        user_dir=Path.home() / ".agenthicc",
    )
    warn_conflicts(_project_plugins)
    renderer._project_plugin_tools = _project_plugins.all_tools
    if _project_plugins.all_tools:
        from rich.console import Console as _C  # noqa: PLC0415
        _C().print(f"[dim]Loaded {len(_project_plugins.all_tools)} plugin "
                   f"tool(s) from .agenthicc/tools/[/dim]")

    # ── MCP server initialisation ─────────────────────────────────────────
    _mcp_registry = None
    if cfg.tools.mcp_servers:
        try:
            from agenthicc.tools.mcp import McpToolRegistry  # noqa: PLC0415
            _mcp_registry = McpToolRegistry(event_processor=processor)
            for srv_cfg in cfg.tools.mcp_servers:
                _mcp_registry.register_server(srv_cfg)
            discovered = await _mcp_registry.discover_all()
            if discovered:
                from rich.console import Console as _Con  # noqa: PLC0415
                _Con().print(f"[dim]MCP: {len(discovered)} tool(s) from {len(cfg.tools.mcp_servers)} server(s)[/dim]")
            renderer._mcp_registry = _mcp_registry
        except Exception as exc:  # noqa: BLE001
            import logging as _log  # noqa: PLC0415
            _log.getLogger(__name__).error("MCP init failed: %s", exc)

    # ── @mention cache ────────────────────────────────────────────────────
    from agenthicc.mentions.cache import MentionCache  # noqa: PLC0415
    _mention_cache = MentionCache()
    renderer._mention_cache = _mention_cache

    # ── conversation store + memory ───────────────────────────────────────
    from lauren_ai._memory import ShortTermMemory  # noqa: PLC0415
    _session_memory = ShortTermMemory(max_tokens=32_000)
    conv_store = ConversationStore()
    _turn_index = [conv_store.next_turn_index(session_id)]

    # On resume: replay history into the transcript and restore LLM memory
    if resume_id:
        import shutil as _sh  # noqa: PLC0415
        from rich.console import Console as _Con  # noqa: PLC0415
        from rich.markdown import Markdown as _Md  # noqa: PLC0415
        from rich.rule import Rule  # noqa: PLC0415
        _con = _Con(highlight=False, markup=True)
        _cols = _sh.get_terminal_size((80, 24)).columns
        _con.print(Rule(f"[dim]resumed session {resume_id[:12]}[/dim]"))
        past_turns = conv_store.load_turns(resume_id)
        for turn in past_turns[-20:]:  # display last 20 Q&A pairs
            if "user" in turn:
                _con.print(f"[dim]❯ {turn['user']}[/dim]")
                _con.print(f"[dim]{'─' * _cols}[/dim]")
            if "assistant" in turn:
                ms = turn.get("model_short", "assistant")
                ts = turn.get("timestamp", time.time())
                hhmmss = time.strftime("%H:%M:%S", time.localtime(ts))
                _con.print(
                    f"[bold cyan]●[/] [bold]assistant ({ms})[/]  [dim]{hhmmss}[/dim]"
                )
                _con.print(_Md(turn["assistant"]), highlight=False)
        # Restore LLM context so the agent remembers past turns
        snapshot = conv_store.load_memory_snapshot(resume_id)
        if snapshot:
            _session_memory.restore(snapshot)

    # Build the lauren-ai runner that calls the LLM
    agent_runner = _build_agent_runner(llm_cfg, transcript=model)

    _MD_SENTINEL = InlineRenderer._MD_SENTINEL

    async def on_intent(text: str) -> None:
        idx = _turn_index[0]
        conv_store.save_turn(session_id, idx, "user", text, time.time())
        turns_before = len(model.turns)

        await _run_agent_turn(
            text, agent_runner, model, renderer, processor,
            session_memory=_session_memory,
            max_agent_turns=cfg.execution.max_agent_turns,
        )

        # Capture the assistant response just added to the transcript
        if len(model.turns) > turns_before:
            last = model.turns[-1]
            content = "\n".join(
                ln.replace(_MD_SENTINEL, "") for ln in getattr(last, "output_lines", getattr(last, "lines", []))
            ).strip()
            ms = last.agent_name.replace("assistant (", "").rstrip(")")
            conv_store.save_turn(session_id, idx, "assistant", content, time.time(), model_short=ms)

        # Persist memory so the next resume sees full context
        conv_store.save_memory_snapshot(session_id, _session_memory.snapshot())
        _turn_index[0] += 1

    # Start ad rotator for free-tier authenticated users
    ad_task: asyncio.Task | None = None
    try:
        from agenthicc.auth import AuthClient  # noqa: PLC0415
        from agenthicc.ads import AdRotator  # noqa: PLC0415
        auth_client = AuthClient()
        bundle = auth_client.current_bundle()
        if bundle is not None and not bundle.is_pro:
            rotator = AdRotator(auth_client=auth_client, processor=processor)
            ad_task = asyncio.create_task(rotator.run())
    except Exception:
        pass  # ads never block startup

    proc_task = asyncio.create_task(processor.run())
    try:
        await renderer.run(on_intent)
    finally:
        proc_task.cancel()
        if ad_task is not None:
            ad_task.cancel()
        await asyncio.gather(proc_task, *(([ad_task] if ad_task else [])), return_exceptions=True)
        conv_store.close()
        if _mcp_registry is not None:
            await _mcp_registry.shutdown()


def _run_tui(args: argparse.Namespace) -> None:
    try:
        from rich.console import Console  # noqa: F401
    except ImportError:
        print(
            "error: TUI requires rich:\n"
            "  pip install agenthicc\n"
            "Or run headless: agenthicc --headless",
            file=sys.stderr,
        )
        sys.exit(1)

    cli_overrides = getattr(args, "set_overrides", [])

    resume_id: str | None = None
    if args.resume:
        resume_id = args.resume
    elif args.continue_session:
        resume_id = _find_latest_session_for_cwd()
        if resume_id is None:
            print("No previous session found for this directory. Starting fresh.")

    try:
        asyncio.run(_run_tui_session(resume_id=resume_id, cli_overrides=cli_overrides))
    except Exception as exc:
        print(f"TUI error: {exc}", file=sys.stderr)
        sys.exit(1)


# ── entry point ───────────────────────────────────────────────────────────────

def main() -> None:
    args = _parse_args()

    if args.command == "config":
        if getattr(args, "config_command", None) == "show":
            _do_config_show(args)
        elif getattr(args, "config_command", None) == "init":
            _do_config_init(args)
        else:
            print("Usage: agenthicc config [show|init]")
        return
    elif args.command == "login":
        asyncio.run(_do_login())
    elif args.command == "logout":
        asyncio.run(_do_logout())
    elif args.command == "whoami":
        _do_whoami()
    elif args.command == "sessions":
        _do_sessions()
    elif args.headless:
        asyncio.run(_run_headless())
    else:
        _run_tui(args)


if __name__ == "__main__":
    main()
