"""Entry point for ``python -m agenthicc`` and the ``agenthicc`` command."""

from __future__ import annotations

import argparse
import asyncio
import json
import os
import sys
import time
import uuid
from pathlib import Path


# ── session index helpers ────────────────────────────────────────────────────

_SESSIONS_DIR  = Path(".agenthicc/sessions")
_SESSION_INDEX = Path(".agenthicc/sessions.json")


def _load_session_index() -> dict:
    if _SESSION_INDEX.exists():
        try:
            return json.loads(_SESSION_INDEX.read_text())
        except Exception:
            return {}
    return {}


def _save_session_index(index: dict) -> None:
    _SESSION_INDEX.parent.mkdir(parents=True, exist_ok=True)
    _SESSION_INDEX.write_text(json.dumps(index, indent=2))


def _register_session(session_id: str) -> None:
    index = _load_session_index()
    index[session_id] = {
        "cwd": os.getcwd(),
        "created_at": time.time(),
        "last_used": time.time(),
        "log_path": str(_SESSIONS_DIR / f"{session_id}.jsonl"),
    }
    _save_session_index(index)


def _touch_session(session_id: str) -> None:
    index = _load_session_index()
    if session_id in index:
        index[session_id]["last_used"] = time.time()
        _save_session_index(index)


def _find_latest_session_for_cwd() -> str | None:
    index = _load_session_index()
    cwd = os.getcwd()
    candidates = [
        (data.get("last_used", 0), sid)
        for sid, data in index.items()
        if data.get("cwd") == cwd
    ]
    return max(candidates)[1] if candidates else None


def _get_session_log_path(session_id: str) -> Path | None:
    index = _load_session_index()
    entry = index.get(session_id)
    if entry:
        return Path(entry["log_path"])
    return None


# ── argument parsing ──────────────────────────────────────────────────────────

def _parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        prog="agenthicc",
        description="Agenthicc — state-driven agent OS for autonomous software engineering",
    )
    parser.add_argument("--headless", action="store_true",
                        help="Run without the TUI; emit JSON-lines to stdout.")
    parser.add_argument("--config", metavar="PATH", default=None,
                        help="Path to agenthicc.toml.")
    parser.add_argument("--version", action="version", version="agenthicc 0.1.0")
    parser.add_argument("--continue", dest="continue_session", action="store_true",
                        help="Continue the most recent session for this directory.")
    parser.add_argument("--resume", metavar="ID", default=None,
                        help="Resume the session with the given ID.")

    parser.add_argument(
        "--set",
        metavar="KEY=VALUE",
        action="append",
        default=[],
        dest="set_overrides",
        help="Override a config key (section.key=value). Can be repeated.",
    )

    subparsers = parser.add_subparsers(dest="command")
    subparsers.add_parser("login",   help="Authenticate with agenthicc.ai")
    subparsers.add_parser("logout",  help="Log out and revoke tokens")
    subparsers.add_parser("whoami",  help="Show current authenticated user")
    subparsers.add_parser("sessions", help="List saved sessions")

    config_parser = subparsers.add_parser("config", help="Manage configuration")
    config_sub = config_parser.add_subparsers(dest="config_command")
    config_sub.add_parser("show", help="Print the merged effective configuration")
    config_init_p = config_sub.add_parser("init", help="Create a template agenthicc.toml")
    config_init_p.add_argument("--force", action="store_true", help="Overwrite existing config")

    return parser.parse_args()


# ── config subcommand ─────────────────────────────────────────────────────────

TEMPLATE_CONFIG = """\
# agenthicc.toml — project configuration
# Generated by: agenthicc config init
# Docs: https://agenthicc.dev/docs/guides/configuration

[execution]
max_concurrent_intents = 10
max_parallel_tasks = 20
agent_pool_size = 30

[memory]
project_memory_path = ".agenthicc/memory"

[security]
default_action = "deny"

[api]
host = "127.0.0.1"
port = 8000
"""


def _do_config_show(args) -> None:
    from agenthicc.config import load_config  # noqa: PLC0415
    cli_overrides = getattr(args, "set_overrides", [])
    config = load_config(cli_overrides=cli_overrides)
    print("# Effective configuration")
    for section_name in ["execution", "memory", "security", "api", "tools"]:
        section = getattr(config, section_name, None)
        if section is None:
            continue
        print(f"\n[{section_name}]")
        for k, v in vars(section).items():
            print(f"{k} = {v!r}")


def _do_config_init(args) -> None:
    target = Path(".agenthicc") / "agenthicc.toml"
    target.parent.mkdir(parents=True, exist_ok=True)
    if target.exists() and not getattr(args, "force", False):
        print(f"{target} already exists. Use --force to overwrite.")
        return
    target.write_text(TEMPLATE_CONFIG)
    print(f"Created {target}")
    print("Tip — add to .gitignore:")
    print("  echo '.agenthicc/' >> .gitignore")
    print("  echo '!.agenthicc/agenthicc.toml' >> .gitignore")


# ── auth subcommands ──────────────────────────────────────────────────────────

async def _do_login() -> None:
    from agenthicc.auth import AuthClient
    client = AuthClient()
    bundle = await client.login()
    print(f"Logged in as {bundle.email}  [plan: {bundle.plan}]")


async def _do_logout() -> None:
    from agenthicc.auth import AuthClient
    await AuthClient().logout()
    print("Logged out.")


def _do_whoami() -> None:
    from agenthicc.auth import AuthClient
    bundle = AuthClient().current_bundle()
    if bundle is None:
        print("Not logged in. Run: agenthicc login")
    else:
        exp = time.strftime("%Y-%m-%d %H:%M", time.localtime(bundle.expires_at))
        print(f"{bundle.email}  plan={bundle.plan}  token_expires={exp}")


def _do_sessions() -> None:
    index = _load_session_index()
    if not index:
        print("No saved sessions.")
        return
    cwd = os.getcwd()
    for sid, data in sorted(index.items(), key=lambda x: x[1].get("last_used", 0), reverse=True):
        marker = " *" if data.get("cwd") == cwd else ""
        last = time.strftime("%Y-%m-%d %H:%M", time.localtime(data.get("last_used", 0)))
        print(f"  {sid[:12]}  {last}  {data.get('cwd', '')} {marker}")


# ── headless mode ─────────────────────────────────────────────────────────────

async def _run_headless() -> None:
    from agenthicc.kernel import AppState, Event, EventProcessor, SecurityPolicy, SystemSettings

    state = AppState.create(settings=SystemSettings(), policy=SecurityPolicy())
    processor = EventProcessor(initial_state=state, persist=False)
    sub = processor.subscribe()
    proc_task = asyncio.create_task(processor.run())
    print(json.dumps({"status": "ready", "mode": "headless"}), flush=True)
    try:
        while True:
            line = await asyncio.get_event_loop().run_in_executor(None, sys.stdin.readline)
            if not line:
                break
            text = line.strip()
            if not text:
                continue
            intent_id = uuid.uuid4().hex
            await processor.emit(Event.create("IntentCreated", {"intent_id": intent_id, "raw_text": text}))
            try:
                snap = await asyncio.wait_for(sub.get(), timeout=2.0)
                intent = snap.intents.get(intent_id)
                print(json.dumps({"event_type": "IntentCreated", "intent_id": intent_id,
                                  "status": intent.status.value if intent else "pending"}), flush=True)
            except asyncio.TimeoutError:
                print(json.dumps({"event_type": "Error", "message": "timeout"}), flush=True)
    finally:
        proc_task.cancel()
        await asyncio.gather(proc_task, return_exceptions=True)


# ── TUI session ───────────────────────────────────────────────────────────────

def _build_agent_runner(llm_cfg: Any, transcript: Any = None) -> Any:
    """Build a lauren-ai AgentRunnerBase wired to a SignalBus for tool-call tracking."""
    if llm_cfg is None:
        return None
    from lauren_ai._agents._runner import AgentRunnerBase  # noqa: PLC0415
    from lauren_ai._module import _build_transport  # noqa: PLC0415
    from lauren_ai._signals import SignalBus  # noqa: PLC0415

    bus = SignalBus()

    if transcript is not None:
        # Capture the current agent_id at signal time via closure over a mutable cell
        _current_agent: list[str] = ["system"]

        @bus.on_any
        async def _route(sig: Any) -> None:
            sig_type = type(sig).__name__
            if sig_type == "ToolCallStarted":
                transcript.add_tool_call(
                    agent_id=_current_agent[0],
                    tool_use_id=getattr(sig, "tool_use_id", ""),
                    name=getattr(sig, "tool_name", ""),
                    args=dict(getattr(sig, "input", {}) or {}),
                )
            elif sig_type == "ToolCallComplete":
                transcript.finish_tool_call(
                    tool_use_id=getattr(sig, "tool_use_id", ""),
                    success=bool(getattr(sig, "success", True)),
                    duration_ms=getattr(sig, "duration_ms", None),
                    error=getattr(sig, "error", None),
                )

        # Expose the agent cell so _run_agent_turn can set it
        bus._current_agent_cell = _current_agent  # type: ignore[attr-defined]

    transport = _build_transport(llm_cfg)
    return AgentRunnerBase(transport=transport, signals=bus)


async def _run_agent_turn(
    text: str,
    runner: Any,
    transcript: Any,
    renderer: Any,
    processor: Any,
    session_memory: Any = None,
    max_agent_turns: int = 200,
) -> None:
    """Run one agent turn: call LLM, stream response into transcript, show Rich spinner."""
    import re as _re  # noqa: PLC0415
    from lauren_ai._agents import agent as agent_decorator, use_tools  # noqa: PLC0415
    from lauren_ai.testing import _build_runner_for_agent  # noqa: PLC0415
    from agenthicc.kernel import Event  # noqa: PLC0415
    from agenthicc.tui.app import _thinking_wave  # noqa: PLC0415
    from agenthicc.agent_tools import AGENT_TOOLS  # noqa: PLC0415
    from rich.live import Live  # noqa: PLC0415
    from rich.text import Text  # noqa: PLC0415

    if runner is None:
        transcript.append_turn("system", "system", time.monotonic())
        transcript.append_line("system", "⚠ No LLM configured. Set ANTHROPIC_API_KEY or OPENAI_API_KEY.")
        return

    # ── resolve model_id FIRST (fixes UnboundLocalError) ──────────────────
    model_id = (
        runner._transport._config.model
        if hasattr(runner._transport, "_config")
        else "unknown"
    )
    model_short = model_id.split("/")[-1]

    # ── kernel event ──────────────────────────────────────────────────────
    intent_id = uuid.uuid4().hex
    await processor.emit(Event.create("IntentCreated", {"intent_id": intent_id, "raw_text": text}))

    agent_id = f"agent-{intent_id[:8]}"
    transcript.append_turn(agent_id, f"assistant ({model_short})", time.monotonic())

    # ── let signal bridge know the current agent ──────────────────────────
    cell = getattr(getattr(runner, "_signals", None), "_current_agent_cell", None)
    if cell is not None:
        cell[0] = agent_id

    # ── status bar + Rich Live spinner ────────────────────────────────────
    renderer._status.active = True
    renderer._status.intent_started_at = time.monotonic()
    renderer._status.input_tokens = 0
    renderer._status.output_tokens = 0

    # Wire ModelCallComplete signal → live token count updates in the spinner.
    # Fires once per LLM turn so counts accumulate in real-time during multi-turn runs.
    _signals = getattr(runner, "_signals", None)

    # Live tool call list shown inside the spinner block while the agent is thinking.
    # Each entry: {"id": str, "name": str, "args": str, "done": bool, "ok": bool, "ms": float|None}
    _live_calls: list[dict] = []
    # Keyed by tool_use_id: (relative_path, original_content) captured before the call.
    _file_snapshots: dict[str, tuple[str, str]] = {}
    # File-editing tool names that warrant a unified diff in the transcript.
    _FILE_EDIT_TOOLS = {"write_file", "patch_file", "append_file"}

    if _signals is not None:
        from lauren_ai._signals import ModelCallComplete as _MCC  # noqa: PLC0415
        from lauren_ai._signals import ToolCallStarted as _TCS, ToolCallComplete as _TCC  # noqa: PLC0415

        @_signals.on(_MCC)
        async def _on_model_complete(sig: Any) -> None:
            usage = getattr(sig, "usage", None)
            if usage:
                renderer._status.input_tokens += getattr(usage, "input_tokens", 0)
                renderer._status.output_tokens += getattr(usage, "output_tokens", 0)
            renderer._status.session_cost_usd += getattr(sig, "cost_usd", 0.0) or 0.0

        @_signals.on(_TCS)
        async def _on_tool_started(sig: Any) -> None:
            args = dict(getattr(sig, "input", {}) or {})
            tool_name = getattr(sig, "tool_name", "")
            tid = getattr(sig, "tool_use_id", "")
            # Format args as Claude Code style: first value only if single, else key=val pairs
            items = list(args.items())
            if len(items) == 1:
                args_str = repr(items[0][1])[:50]
            elif items:
                args_str = ", ".join(f"{k}={repr(v)[:25]}" for k, v in items[:3])
                if len(items) > 3:
                    args_str += ", …"
            else:
                args_str = ""
            _live_calls.append({
                "id": tid,
                "name": tool_name,
                "args": args_str,
                "done": False,
                "ok": True,
                "ms": None,
            })
            # Snapshot file content before write/patch so we can produce a diff later.
            if tool_name in _FILE_EDIT_TOOLS:
                rel_path = args.get("path", "")
                if rel_path:
                    full = os.path.join(os.getcwd(), rel_path) if not os.path.isabs(rel_path) else rel_path
                    try:
                        original = await asyncio.to_thread(
                            lambda p=full: open(p).read() if os.path.exists(p) else ""
                        )
                        _file_snapshots[tid] = (rel_path, original)
                    except Exception:
                        pass

        @_signals.on(_TCC)
        async def _on_tool_complete(sig: Any) -> None:
            import difflib as _dl  # noqa: PLC0415
            tid = getattr(sig, "tool_use_id", "")
            for entry in _live_calls:
                if entry["id"] == tid:
                    entry["done"] = True
                    entry["ok"] = bool(getattr(sig, "success", True))
                    entry["ms"] = getattr(sig, "duration_ms", None)
                    break
            # Generate unified diff for file-editing tools and store as transcript output.
            if tid in _file_snapshots:
                rel_path, original = _file_snapshots.pop(tid)
                full = os.path.join(os.getcwd(), rel_path) if not os.path.isabs(rel_path) else rel_path
                try:
                    new_content = await asyncio.to_thread(
                        lambda p=full: open(p).read() if os.path.exists(p) else ""
                    )
                    diff = "".join(_dl.unified_diff(
                        original.splitlines(keepends=True),
                        new_content.splitlines(keepends=True),
                        fromfile=f"a/{rel_path}",
                        tofile=f"b/{rel_path}",
                        lineterm="",
                    ))
                    if diff:
                        transcript.finish_tool_call(tool_use_id=tid, output=diff)
                        for entry in _live_calls:
                            if entry["id"] == tid:
                                entry["diff"] = diff
                                break
                except Exception:
                    pass

    # Build the agent class with tools so it can actually DO things
    @agent_decorator(
        model=model_id,
        system=(
            "You are a capable AI assistant with access to filesystem, shell, "
            "and git tools. Use them directly to complete tasks. "
            "Give concise responses. Show command output when relevant. "
            "Never invent file contents — always read them first."
        ),
    )
    @use_tools(*AGENT_TOOLS)
    class _AgenthiccAgent: ...

    # Use _build_runner_for_agent so tools are resolved correctly from @use_tools metadata
    _agent_instance = _AgenthiccAgent()
    _active_runner = _build_runner_for_agent(
        _agent_instance,
        runner._transport,
        signals=getattr(runner, "_signals", None),
    )

    live = Live(refresh_per_second=12, transient=True)
    live.start()

    from agenthicc.tui.transcript import TranscriptModel as _TM  # noqa: PLC0415
    _MAX_VISIBLE_CALLS = _TM.MAX_VISIBLE_TOOL_CALLS

    # CTRL+O toggles expanded/collapsed; ↑/↓ scroll in expanded mode.
    _expanded = [False]
    _scroll_offset = [0]  # first visible call_line index when expanded

    async def _watch_ctrlO() -> None:
        """Poll stdin for CTRL+O and arrow keys while the agent is thinking."""
        import select as _sel, tty as _tty, termios as _tm  # noqa: PLC0415
        fd = sys.stdin.fileno()
        try:
            old = _tm.tcgetattr(fd)
            _tty.setcbreak(fd)
        except Exception:
            return
        try:
            while True:
                await asyncio.sleep(0.05)
                r, _, _ = _sel.select([fd], [], [], 0)
                if not r:
                    continue
                ch = os.read(fd, 1)
                if ch == b"\x0f":           # CTRL+O — toggle and reset scroll
                    _expanded[0] = not _expanded[0]
                    _scroll_offset[0] = 0
                elif ch == b"\x1b":         # possible escape sequence (arrow keys)
                    r2, _, _ = _sel.select([fd], [], [], 0.05)
                    if r2:
                        rest = os.read(fd, 2)
                        seq = ch + rest
                        if _expanded[0]:
                            if seq == b"\x1b[A":    # up arrow
                                _scroll_offset[0] = max(0, _scroll_offset[0] - 1)
                            elif seq == b"\x1b[B":  # down arrow
                                _scroll_offset[0] += 1  # clamped in _spin()
        except asyncio.CancelledError:
            pass
        finally:
            try:
                _tm.tcsetattr(fd, _tm.TCSADRAIN, old)
            except Exception:
                pass

    async def _spin() -> None:
        import shutil as _sh  # noqa: PLC0415
        from rich.markup import render as _mk  # noqa: PLC0415
        while True:
            elapsed = time.monotonic() - renderer._status.intent_started_at
            frame = _thinking_wave(renderer._status.spinner_frame)
            header = (
                f" {frame}  [dim]{elapsed:.1f}s  │[/dim]"
                f"  [cyan]↑ {renderer._status.input_tokens:,}[/cyan]"
                f"  [green]↓ {renderer._status.output_tokens:,}[/green]"
            )
            call_lines: list[str] = []
            for call in _live_calls:
                name = call["name"]
                args = call["args"]
                if call["done"]:
                    icon = "[green]✓[/green]" if call["ok"] else "[red]✗[/red]"
                    ms = f"  [dim]{call['ms']:.0f}ms[/dim]" if call["ms"] else ""
                    call_lines.append(
                        f"   [dim]⎿[/dim] [bold]{name}[/bold][dim]({args})[/dim]  {icon}{ms}"
                    )
                    diff_text = call.get("diff", "")
                    if diff_text:
                        diff_lines_all = diff_text.splitlines()
                        diff_preview = diff_lines_all[:8]
                        for dl in diff_preview:
                            if dl.startswith("+++") or dl.startswith("---"):
                                call_lines.append(f"      [dim]{dl}[/dim]")
                            elif dl.startswith("@@"):
                                call_lines.append(f"      [dim cyan]{dl}[/dim cyan]")
                            elif dl.startswith("+"):
                                call_lines.append(f"      [green]{dl}[/green]")
                            elif dl.startswith("-"):
                                call_lines.append(f"      [red]{dl}[/red]")
                            else:
                                call_lines.append(f"      [dim]{dl}[/dim]")
                        if len(diff_lines_all) > 8:
                            call_lines.append(
                                f"      [dim]… {len(diff_lines_all) - 8} more diff lines[/dim]"
                            )
                else:
                    call_lines.append(
                        f"   [dim]⎿[/dim] [bold]{name}[/bold][dim]({args})[/dim]  [dim]…[/dim]"
                    )
            if _expanded[0]:
                # Compute how many lines fit below the header row.
                rows = _sh.get_terminal_size((80, 24)).lines
                viewport = max(4, rows - 3)   # reserve header + indicator + slack
                total = len(call_lines)
                # Clamp scroll so we never scroll past the last entry.
                _scroll_offset[0] = min(_scroll_offset[0], max(0, total - viewport))
                off = _scroll_offset[0]
                visible = call_lines[off : off + viewport]
                end = min(off + viewport, total)
                indicator = (
                    f"   [dim]{off + 1}–{end} of {total}"
                    f"  ↑↓ to scroll  ctrl+O to collapse[/dim]"
                )
                call_lines = visible + [indicator]
            elif len(call_lines) > _MAX_VISIBLE_CALLS:
                hidden = len(call_lines) - _MAX_VISIBLE_CALLS
                call_lines = call_lines[:_MAX_VISIBLE_CALLS] + [
                    f"   [dim]… and {hidden} more tool call{'s' if hidden != 1 else ''}  "
                    f"[ctrl+O to expand][/dim]"
                ]
            live.update(_mk("\n".join([header] + call_lines)))
            renderer._status.spinner_frame += 1
            await asyncio.sleep(0.05)

    spin_task = asyncio.create_task(_spin())
    ctrlO_task = asyncio.create_task(_watch_ctrlO())

    try:
        from lauren_ai._config import AgentConfig as _AgentConfig  # noqa: PLC0415
        _cfg = _AgentConfig(
            max_turns=max_agent_turns,
            parallel_tool_calls=True,
        )
        response = await _active_runner.run(
            _agent_instance,
            text,
            memory=session_memory,
            config_override=_cfg,
        )
        content = response.content or ""
        # Strip any residual XML that slipped through
        content = _re.sub(r"<tool_call>.*?</tool_call>", "", content, flags=_re.DOTALL)
        content = _re.sub(r"<[^>]+>", "", content)
        content = content.strip()
        # If the model completed its work via tool calls and has nothing to add,
        # skip the prose block entirely rather than printing "(no response)".
        if not content and response.tool_calls_made:
            content = ""   # will be skipped below
        elif not content:
            content = "(no response)"
        # Token counts + cost already accumulated via ModelCallComplete signal handler above
    except Exception as exc:
        content = f"⚠ Error: {exc}"
    finally:
        spin_task.cancel()
        ctrlO_task.cancel()
        await asyncio.gather(spin_task, ctrlO_task, return_exceptions=True)
        live.stop()
        renderer._status.active = False
        renderer._status.completed_agents += 1

    # Only append prose if there's something to say
    if content:
        from agenthicc.tui.app import InlineRenderer  # noqa: PLC0415
        transcript.append_line(agent_id, InlineRenderer._MD_SENTINEL + content)

    await processor.emit(
        Event.create("IntentStatusChanged", {"intent_id": intent_id, "status": "complete"})
    )


async def _run_tui_session(resume_id: str | None = None, cli_overrides: list[str] | None = None) -> None:
    from agenthicc.kernel import AppState, Event, EventProcessor, SecurityPolicy, SystemSettings
    from agenthicc.kernel.reducer import root_reducer
    from agenthicc.kernel.processor import restore_from_log
    from agenthicc.tui.transcript import TranscriptModel
    from agenthicc.tui.events import TUIEventAdapter
    from agenthicc.tui.app import InlineRenderer
    from agenthicc.config import load_config, build_llm_config
    from agenthicc.conversation_store import ConversationStore  # noqa: PLC0415

    session_id = resume_id or uuid.uuid4().hex
    _SESSIONS_DIR.mkdir(parents=True, exist_ok=True)
    log_path = str(_SESSIONS_DIR / f"{session_id}.jsonl")

    settings = SystemSettings(
        event_log_path=log_path,
        snapshot_path=".agenthicc/snapshot.json",
    )
    state = AppState.create(settings=settings, policy=SecurityPolicy())

    # Restore from log when resuming
    if resume_id:
        log_file = _get_session_log_path(resume_id)
        if log_file and log_file.exists():
            state = await restore_from_log(str(log_file), state, root_reducer)
        _touch_session(resume_id)
    else:
        _register_session(session_id)

    processor = EventProcessor(initial_state=state, persist=True)
    model = TranscriptModel()
    adapter = TUIEventAdapter(model)
    adapter.subscribe_to(processor)

    # Load config and build LLM transport for agent runs
    cfg = load_config(cli_overrides=cli_overrides or [])
    try:
        llm_cfg = build_llm_config(cfg.execution)
    except ValueError as exc:
        from rich.console import Console  # noqa: PLC0415
        Console().print(f"[red]LLM config error: {exc}[/red]\n"
                        "[dim]Set ANTHROPIC_API_KEY or OPENAI_API_KEY env var, or use --set execution.provider=...[/dim]",
                        markup=True)
        llm_cfg = None

    renderer = InlineRenderer(
        model, adapter,
        base_path=os.getcwd(),
        history_file=".agenthicc/history",
    )
    renderer._processor = processor
    renderer._status.session_id = (
        f"{cfg.execution.provider}/{cfg.execution.effective_model()}"
    )
    renderer._status.resume_id = session_id

    # ── conversation store + memory ───────────────────────────────────────
    from lauren_ai._memory import ShortTermMemory  # noqa: PLC0415
    _session_memory = ShortTermMemory(max_tokens=32_000)
    conv_store = ConversationStore()
    _turn_index = [conv_store.next_turn_index(session_id)]

    # On resume: replay history into the transcript and restore LLM memory
    if resume_id:
        import shutil as _sh  # noqa: PLC0415
        from rich.console import Console as _Con  # noqa: PLC0415
        from rich.markdown import Markdown as _Md  # noqa: PLC0415
        from rich.rule import Rule  # noqa: PLC0415
        _con = _Con(highlight=False, markup=True)
        _cols = _sh.get_terminal_size((80, 24)).columns
        _con.print(Rule(f"[dim]resumed session {resume_id[:12]}[/dim]"))
        past_turns = conv_store.load_turns(resume_id)
        for turn in past_turns[-20:]:  # display last 20 Q&A pairs
            if "user" in turn:
                _con.print(f"[dim]❯ {turn['user']}[/dim]")
                _con.print(f"[dim]{'─' * _cols}[/dim]")
            if "assistant" in turn:
                ms = turn.get("model_short", "assistant")
                ts = turn.get("timestamp", time.time())
                hhmmss = time.strftime("%H:%M:%S", time.localtime(ts))
                _con.print(
                    f"[bold cyan]●[/] [bold]assistant ({ms})[/]  [dim]{hhmmss}[/dim]"
                )
                _con.print(_Md(turn["assistant"]), highlight=False)
        # Restore LLM context so the agent remembers past turns
        snapshot = conv_store.load_memory_snapshot(resume_id)
        if snapshot:
            _session_memory.restore(snapshot)

    # Build the lauren-ai runner that calls the LLM
    agent_runner = _build_agent_runner(llm_cfg, transcript=model)

    _MD_SENTINEL = InlineRenderer._MD_SENTINEL

    async def on_intent(text: str) -> None:
        idx = _turn_index[0]
        conv_store.save_turn(session_id, idx, "user", text, time.time())
        turns_before = len(model.turns)

        await _run_agent_turn(
            text, agent_runner, model, renderer, processor,
            session_memory=_session_memory,
            max_agent_turns=cfg.execution.max_agent_turns,
        )

        # Capture the assistant response just added to the transcript
        if len(model.turns) > turns_before:
            last = model.turns[-1]
            content = "\n".join(
                ln.replace(_MD_SENTINEL, "") for ln in last.lines
            ).strip()
            ms = last.agent_name.replace("assistant (", "").rstrip(")")
            conv_store.save_turn(session_id, idx, "assistant", content, time.time(), model_short=ms)

        # Persist memory so the next resume sees full context
        conv_store.save_memory_snapshot(session_id, _session_memory.snapshot())
        _turn_index[0] += 1

    # Start ad rotator for free-tier authenticated users
    ad_task: asyncio.Task | None = None
    try:
        from agenthicc.auth import AuthClient, NotLoggedInError  # noqa: PLC0415
        from agenthicc.ads import AdRotator  # noqa: PLC0415
        auth_client = AuthClient()
        bundle = auth_client.current_bundle()
        if bundle is not None and not bundle.is_pro:
            rotator = AdRotator(auth_client=auth_client, processor=processor)
            ad_task = asyncio.create_task(rotator.run())
    except Exception:
        pass  # ads never block startup

    proc_task = asyncio.create_task(processor.run())
    try:
        await renderer.run(on_intent)
    finally:
        proc_task.cancel()
        if ad_task is not None:
            ad_task.cancel()
        await asyncio.gather(proc_task, *(([ad_task] if ad_task else [])), return_exceptions=True)
        conv_store.close()


def _run_tui(args: argparse.Namespace) -> None:
    try:
        from rich.console import Console  # noqa: F401
        from prompt_toolkit import PromptSession  # noqa: F401
    except ImportError:
        print(
            "error: TUI requires rich and prompt_toolkit:\n"
            "  pip install agenthicc[tui]\n"
            "Or run headless: agenthicc --headless",
            file=sys.stderr,
        )
        sys.exit(1)

    cli_overrides = getattr(args, "set_overrides", [])

    resume_id: str | None = None
    if args.resume:
        resume_id = args.resume
    elif args.continue_session:
        resume_id = _find_latest_session_for_cwd()
        if resume_id is None:
            print("No previous session found for this directory. Starting fresh.")

    try:
        asyncio.run(_run_tui_session(resume_id=resume_id, cli_overrides=cli_overrides))
    except Exception as exc:
        print(f"TUI error: {exc}", file=sys.stderr)
        sys.exit(1)


# ── entry point ───────────────────────────────────────────────────────────────

def main() -> None:
    args = _parse_args()

    if args.command == "config":
        if getattr(args, "config_command", None) == "show":
            _do_config_show(args)
        elif getattr(args, "config_command", None) == "init":
            _do_config_init(args)
        else:
            print("Usage: agenthicc config [show|init]")
        return
    elif args.command == "login":
        asyncio.run(_do_login())
    elif args.command == "logout":
        asyncio.run(_do_logout())
    elif args.command == "whoami":
        _do_whoami()
    elif args.command == "sessions":
        _do_sessions()
    elif args.headless:
        asyncio.run(_run_headless())
    else:
        _run_tui(args)


if __name__ == "__main__":
    main()
