"""Generate the standalone PDF builder used by :mod:`make_book`.

The workflow deliberately emits a normal Python program instead of hiding the
build in the runner.  A generated book can therefore be rebuilt later, from a
shell or CI, without an agent session.  The template follows the same
source-discovery, Pandoc, multi-pass XeLaTeX, cover-attachment, and cleanup
stages as the Fit-for-Hyrox reference builders.
"""

from __future__ import annotations

import os
import re
import tempfile
from pathlib import Path


def slugify_book_title(title: str, *, fallback: str = "book") -> str:
    """Return a safe, stable filename slug for a generated book title."""

    slug = re.sub(r"[^a-z0-9]+", "-", title.casefold()).strip("-")
    return slug or fallback


def build_book_script(
    *,
    title: str,
    author: str,
    book_root: Path | str = ".",
) -> str:
    """Render the self-contained ``build_book.py`` source for one book.

    Only metadata is interpolated into the template.  The generated program
    discovers all content relative to the configured book root.  The generated
    file itself is kept beside the run's book sources, so the generated book
    directory is self-contained and can be rebuilt without an agent session.
    """

    safe_title = title.strip() or "Untitled Book"
    safe_author = author.strip() or "Anonymous"
    slug = slugify_book_title(safe_title)
    source_root = str(Path(book_root).expanduser().resolve())

    return rf'''#!/usr/bin/env python3
"""Rebuild the configured book as a print-ready PDF.

Sources are discovered below the configured book root in this order:
``front-matter/``, ``chapters/``, and ``back-matter/``.  The output defaults to
``dist/<dated filename>.pdf`` and can be overridden with ``--out``.

Requirements: pandoc and xelatex on PATH.  Pillow and pypdf are optional; when
both are installed, ``assets/cover.(png|jpg|jpeg)`` is attached as page one.
"""

from __future__ import annotations

import argparse
import re
import shutil
import subprocess
import sys
import tempfile
from datetime import datetime
from pathlib import Path

SCRIPT_DIR = Path(__file__).resolve().parent
ROOT = Path({source_root!r})
TITLE = {safe_title!r}
AUTHOR = {safe_author!r}
SLUG = {slug!r}
TRIM_W_IN = 6.0
TRIM_H_IN = 9.0
COVER_DPI = 600


class BuildError(RuntimeError):
    """Raised when an external build stage cannot produce the PDF."""


def log(message: str) -> None:
    print(f"[build_book] {{message}}", flush=True)


def run(command: list[str], *, cwd: Path = ROOT) -> subprocess.CompletedProcess[str]:
    """Run one build command while retaining a useful bounded diagnostic."""

    log("+ " + " ".join(str(part) for part in command))
    result = subprocess.run(
        [str(part) for part in command],
        cwd=str(cwd),
        capture_output=True,
        text=True,
        encoding="utf-8",
        errors="replace",
    )
    if result.returncode != 0:
        diagnostic = (result.stderr or result.stdout).strip()
        if diagnostic:
            log(diagnostic[-4000:])
    return result


def source_files() -> list[Path]:
    """Discover markdown sources in deterministic publication order."""

    files: list[Path] = []
    for directory in ("front-matter", "chapters", "back-matter"):
        files.extend(sorted((ROOT / directory).glob("*.md"), key=lambda path: path.name))
    if not files:
        raise BuildError("no markdown sources found in front-matter/, chapters/, or back-matter/")
    return files


def write_header(path: Path) -> None:
    """Write the KDP paperback LaTeX header used by the generated build."""

    path.write_text(
        r"""% Generated by build_book.py — 6 x 9 inch paperback trim.
\usepackage{{xcolor}}
\usepackage{{sectsty}}
\usepackage{{textcomp}}
\usepackage{{graphicx}}
\usepackage{{geometry}}
\geometry{{paperwidth=6.0in,paperheight=9.0in,margin=0.75in}}
\definecolor{{accent}}{{HTML}}{{1F4E79}}
\definecolor{{accentlight}}{{HTML}}{{2E74B5}}
\allsectionsfont{{\color{{accent}}}}
\chapterfont{{\color{{accent}}\Large}}
\sectionfont{{\color{{accentlight}}\normalsize}}
\usepackage{{fancyhdr}}
\pagestyle{{fancy}}
\fancyhf{{}}
\fancyhead[L]{{\small\textit{{\leftmark}}}}
\fancyhead[R]{{\small\thepage}}
\renewcommand{{\headrulewidth}}{{0.4pt}}
\renewcommand{{\chaptermark}}[1]{{\markboth{{#1}}{{}}}}
\renewcommand{{\sectionmark}}[1]{{\markright{{}}}}
% Keep TOC page numbers right-aligned without dotted leaders.
\usepackage{{tocloft}}
\renewcommand{{\cftdotfill}}[1]{{\hfill}}
\renewcommand{{\cftchapdotsep}}{{\cftnodots}}
\setcounter{{tocdepth}}{{2}}
""",
        encoding="utf-8",
    )


def postprocess_tex(path: Path) -> None:
    """Remove duplicate title/contents containers emitted by Pandoc."""

    source = path.read_text(encoding="utf-8")
    source = source.replace("\\maketitle\n", "")
    source = re.sub(
        r"\\chapter\\{{Contents\\}}\\label\\{{contents\\}}\\n\\n\\newpage\\n\\n",
        "",
        source,
        count=1,
    )
    source = source.replace("\\frontmatter\n\\tableofcontents\n", "\\frontmatter\n\\clearpage\n\\tableofcontents\n\\clearpage\n\\mainmatter\n", 1)
    path.write_text(source, encoding="utf-8")


def _cover_path() -> Path | None:
    for name in ("cover.png", "cover.jpg", "cover.jpeg", "front-cover.png", "front-cover.jpg"):
        candidate = ROOT / "assets" / name
        if candidate.is_file():
            return candidate
    return None


def _cover_page(image_path: Path, destination: Path) -> bool:
    """Render a cover image onto a 6x9 inch PDF page, if Pillow is present."""

    try:
        from PIL import Image
    except ImportError:
        log("Pillow is not installed; leaving the cover unattached")
        return False

    try:
        image = Image.open(image_path)
        if image.mode not in ("RGB", "L"):
            image = image.convert("RGB")
        page_width = round(TRIM_W_IN * COVER_DPI)
        page_height = round(TRIM_H_IN * COVER_DPI)
        margin = round(0.25 * COVER_DPI)
        scale = min((page_width - 2 * margin) / image.width, (page_height - 2 * margin) / image.height)
        resized = image.resize(
            (max(1, round(image.width * scale)), max(1, round(image.height * scale))),
            Image.Resampling.LANCZOS,
        )
        canvas = Image.new("RGB", (page_width, page_height), "white")
        canvas.paste(resized, ((page_width - resized.width) // 2, (page_height - resized.height) // 2))
        canvas.save(destination, "PDF", resolution=COVER_DPI)
        return True
    except Exception as exc:  # pragma: no cover - dependency-specific failures
        log(f"cover conversion failed; continuing without cover: {{exc}}")
        return False


def attach_cover(pdf_path: Path) -> Path:
    """Prepend the optional user-supplied cover while preserving the PDF body."""

    cover = _cover_path()
    if cover is None:
        return pdf_path
    try:
        from pypdf import PdfReader, PdfWriter
    except ImportError:
        log("pypdf is not installed; leaving the cover unattached")
        return pdf_path

    temporary = Path(tempfile.mkdtemp(prefix="build_book_cover_", dir=str(ROOT)))
    try:
        cover_pdf = temporary / "cover.pdf"
        if not _cover_page(cover, cover_pdf):
            return pdf_path
        writer = PdfWriter()
        for page in PdfReader(str(cover_pdf)).pages:
            writer.add_page(page)
        writer.append(PdfReader(str(pdf_path)))
        combined = temporary / "combined.pdf"
        with combined.open("wb") as handle:
            writer.write(handle)
        shutil.move(str(combined), str(pdf_path))
        log(f"attached cover {{cover.name}} as page one")
        return pdf_path
    finally:
        shutil.rmtree(temporary, ignore_errors=True)


def default_output() -> Path:
    stamp = datetime.now().strftime("%d %b %Y %H%M")
    return ROOT / "dist" / f"{{SLUG}} {{stamp}}.pdf"


def build(output: Path, *, keep_intermediates: bool = False) -> Path:
    """Build and return the final PDF path."""

    for executable in ("pandoc", "xelatex"):
        if shutil.which(executable) is None:
            raise BuildError(f"{{executable}} not found on PATH")
    sources = source_files()
    output = output if output.is_absolute() else ROOT / output
    output.parent.mkdir(parents=True, exist_ok=True)
    build_dir = ROOT / ".build_book"
    build_dir.mkdir(exist_ok=True)
    try:
        header = build_dir / "header.tex"
        tex = build_dir / "book.tex"
        pdf = build_dir / "book.pdf"
        write_header(header)
        result = run([
            "pandoc", *[str(path) for path in sources], "-s",
            "--top-level-division=chapter", "--toc", "--toc-depth=2",
            "-H", str(header), "--resource-path", str(ROOT),
            "--metadata", f"title={{TITLE}}", "--metadata", f"author={{AUTHOR}}",
            "--metadata", "lang=en", "-o", str(tex),
        ])
        if result.returncode != 0:
            raise BuildError("pandoc failed")
        postprocess_tex(tex)

        passes = 2
        for pass_number in range(1, 4):
            result = run([
                "xelatex", "-interaction=nonstopmode", "-halt-on-error",
                f"-output-directory={{build_dir}}", str(tex),
            ])
            if result.returncode != 0 and not pdf.exists():
                raise BuildError("xelatex failed before producing a PDF")
            if pass_number >= passes:
                log_text = (build_dir / "book.log").read_text(encoding="utf-8", errors="replace") if (build_dir / "book.log").exists() else ""
                if "Rerun to get cross-references right" in log_text or "Label(s) may have changed" in log_text:
                    passes = pass_number + 1
                    continue
                break
        if not pdf.is_file() or pdf.read_bytes()[:4] != b"%PDF":
            raise BuildError("xelatex finished without a valid PDF")
        shutil.copyfile(pdf, output)
        attach_cover(output)
        log(f"PDF -> {{output}}")
        return output
    finally:
        if not keep_intermediates:
            shutil.rmtree(build_dir, ignore_errors=True)


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--out", "-o", type=Path, default=None, help="output PDF path")
    parser.add_argument("--keep-intermediates", "--keep", action="store_true")
    args = parser.parse_args(argv)
    try:
        build(args.out or default_output(), keep_intermediates=args.keep_intermediates)
    except BuildError as exc:
        print(f"build_book: error: {{exc}}", file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
'''


def write_build_book_script(
    script_dir: Path,
    *,
    title: str,
    author: str,
    book_root: Path | str | None = None,
) -> Path:
    """Atomically create or refresh ``script_dir/build_book.py``.

    ``book_root`` is where the generated book sources and ``dist/`` live.  It
    defaults to ``script_dir`` for callers that generate a self-contained
    temporary book in tests or tooling.
    """

    script_dir = script_dir.expanduser()
    script_dir.mkdir(parents=True, exist_ok=True)
    destination = script_dir / "build_book.py"
    source_root = Path(book_root).expanduser() if book_root is not None else script_dir
    handle = tempfile.NamedTemporaryFile(
        mode="w",
        encoding="utf-8",
        dir=script_dir,
        prefix=".build_book.",
        suffix=".tmp",
        delete=False,
    )
    temporary = Path(handle.name)
    try:
        with handle:
            handle.write(build_book_script(title=title, author=author, book_root=source_root))
        os.chmod(temporary, 0o755)
        os.replace(temporary, destination)
    except BaseException:
        temporary.unlink(missing_ok=True)
        raise
    return destination


__all__ = ["build_book_script", "slugify_book_title", "write_build_book_script"]
