#!/usr/bin/env python3
"""End-to-end build script for 'Fit for HYROX' (6 x 9 in edition).

Compiles the markdown sources into a polished PDF via pandoc -> LaTeX ->
pdflatex and a matching reflowable EPUB via pandoc. The PDF page order is:
Front cover -> TOC -> Preface -> Chapters -> Index -> Back cover.

The covers are END-USER supplied:
  - front: assets/fit-for-hyrox-front-cover.png (page 1)
  - back:  assets/fit-for-hyrox-back-cover.png  (last page)
Both are rendered at 600 DPI on 6 x 9 in pages and merged with pypdf,
preserving the PDF outline.

Usage:
    python3 build_pdf.py [--keep-intermediates]

Produces:
    dist/Fit for HYROX <timestamp>.pdf
    dist/Fit for HYROX <timestamp>.epub
"""
from __future__ import annotations

import re
import shutil
import subprocess
import sys
import zipfile
from datetime import datetime
from pathlib import Path

HERE = Path(__file__).resolve().parent
TITLE = "Fit for HYROX: The Beginner's Guide to Training, Race Preparation, and Building the Strength, Endurance, and Confidence to Perform Your Best"
AUTHOR = "Ritchie Cheng"
SLUG = "Fit-for-HYROX"

FRONT = sorted((HERE / "front-matter").glob("*.md"))
CHAPTERS = sorted((HERE / "chapters").glob("*.md"))
BACK = sorted((HERE / "back-matter").glob("*.md"))
COVER = HERE / "assets" / "fit-for-hyrox-front-cover.png"
BACK_COVER = HERE / "assets" / "fit-for-hyrox-back-cover.png"

# 6 x 9 in trim (KDP paperback); 600 DPI for the rasterised cover pages.
TRIM_W_IN, TRIM_H_IN = 6.0, 9.0
TRIM_W_PT, TRIM_H_PT = round(TRIM_W_IN * 72), round(TRIM_H_IN * 72)  # 432 x 648
COVER_DPI = 600

ACCENT = "1F4E79"      # deep navy — book accent (planned in the TOC phase)
ACCENT_2 = "2E74B5"    # lighter blue for h2

# Non-ASCII glyphs used in the sources that pdflatex needs declared.
UNICODE_DECLS = r"""
\ifdefined\DeclareUnicodeCharacter
  \DeclareUnicodeCharacter{2014}{---}     % em dash
  \DeclareUnicodeCharacter{2013}{--}      % en dash
  \DeclareUnicodeCharacter{00D7}{$\times$}
  \DeclareUnicodeCharacter{2192}{$\rightarrow$}
  \DeclareUnicodeCharacter{2610}{$\square$}   % ballot box
  \DeclareUnicodeCharacter{2212}{$-$}
  \DeclareUnicodeCharacter{2265}{$\geq$}
  \DeclareUnicodeCharacter{00B0}{\textdegree}
\fi
"""

EPUB_CSS = """\
/* Generated by build_book.py; EPUB readers reflow this content. */
img { max-width: 100%; height: auto; }
figure { max-width: 100%; margin: 1em 0; }
figcaption { margin-top: 0.4em; font-size: 0.9em; color: #333; }
table { max-width: 100%; border-collapse: collapse; }
th, td { padding: 0.3em 0.5em; }
body { font-family: serif; line-height: 1.45; }
h1, h2, h3 { color: #1F4E79; }
"""


def run(cmd, **kw):
    print("+", " ".join(str(c) for c in cmd))
    return subprocess.run([str(c) for c in cmd], **kw)


def dist_name(ext: str = ".pdf") -> str:
    """Return the dated dist filename, e.g. 'Fit for HYROX 09 Aug 2026 1810.pdf'."""
    stamp = datetime.now().strftime("%d %b %Y %H%M")
    return f"Fit for HYROX {stamp}{ext}"


def write_header_tex(path: Path) -> None:
    """LaTeX header: 6x9 geometry, black headings, no-dot TOC, Unicode."""
    path.write_text(
        rf"""% header.tex — book polish for Fit for HYROX (6 x 9 in)
\usepackage{{xcolor}}
\usepackage{{sectsty}}
\usepackage{{textcomp}}
\usepackage{{graphicx}}
\usepackage{{geometry}}
\geometry{{paperwidth={TRIM_W_IN}in,paperheight={TRIM_H_IN}in,margin=1in}}
\graphicspath{{{{../}}}}
\definecolor{{accent}}{{HTML}}{{{ACCENT}}}
\definecolor{{accentl}}{{HTML}}{{{ACCENT_2}}}
\allsectionsfont{{\color{{black}}}}
\chapterfont{{\color{{black}}\Large}}
\sectionfont{{\color{{black}}\normalsize}}
% Tables: smaller font so long cells wrap inside the 6x9 margins.
\AtBeginEnvironment{{longtable}}{{\small}}
\setlength{{\tabcolsep}}{{4pt}}
% Page headers: show only the short chapter title (not the long section
% title), so running heads never overflow the 6x9 text width.
\usepackage{{fancyhdr}}
\pagestyle{{fancy}}
\fancyhf{{}}
\fancyhead[L]{{\small\textit{{\leftmark}}}}
\fancyhead[R]{{\small\thepage}}
\renewcommand{{\headrulewidth}}{{0.4pt}}
\renewcommand{{\chaptermark}}[1]{{\markboth{{#1}}{{}}}}
\renewcommand{{\sectionmark}}[1]{{\markright{{}}}}
% TOC without dotted leaders (page numbers stay right-aligned via \hfill)
\usepackage{{tocloft}}
\renewcommand{{\cftdotfill}}[1]{{\hfill}}
\renewcommand{{\cftchapdotsep}}{{\cftnodots}}
\setcounter{{tocdepth}}{{1}}
{UNICODE_DECLS}
""",
        encoding="utf-8",
    )


def postprocess_tex(tex: Path) -> None:
    """Order the pages TOC -> Preface -> ... -> Index (no cover in the tex;
    covers are attached afterwards with pypdf at 600 DPI)."""
    src = tex.read_text(encoding="utf-8")

    # 1. Drop pandoc's auto \maketitle (no title page — the cover replaces it).
    src = src.replace("\\maketitle\n", "")

    # 2. Anchor on the frontmatter block pandoc emits.
    toc_block = "\\frontmatter\n\\tableofcontents\n"
    replacement = (
        "\\frontmatter\n"
        "\\clearpage\n"
        "\\tableofcontents\n"
        "\\clearpage\n"
        "\\mainmatter\n"
    )
    if toc_block in src:
        src = src.replace(toc_block, replacement, 1)
    else:
        src = src.replace(
            "\\tableofcontents\n",
            "\\clearpage\n\\tableofcontents\n\\clearpage\n",
            1,
        )

    # 3. Remove the empty 'Contents' container chapter — the toolchain's
    #    \tableofcontents already supplies the Contents heading and listing.
    src = re.sub(
        r"\\chapter\{Contents\}\\label\{contents\}\\n\\n\\newpage\\n\\n",
        "",
        src,
        count=1,
    )

    tex.write_text(src, encoding="utf-8")


def build_epub(sources: list[Path], output: Path, build_dir: Path) -> bool:
    """Build and validate the matching reflowable EPUB output."""
    css = build_dir / "epub.css"
    css.write_text(EPUB_CSS, encoding="utf-8")
    result = run([
        "pandoc",
        *sources,
        "--toc",
        "--toc-depth=2",
        "--split-level=1",
        "--metadata", f"title={TITLE}",
        "--metadata", f"author={AUTHOR}",
        "--metadata", "lang=en",
        "--css", css,
        "--resource-path", str(HERE),
        "-o", output,
    ])
    if result.returncode != 0:
        print("pandoc failed while building the EPUB")
        return False
    try:
        with zipfile.ZipFile(output) as archive:
            names = set(archive.namelist())
            if "mimetype" not in names or not any(name.endswith(".opf") for name in names):
                print("EPUB missing mimetype or OPF metadata")
                return False
            if archive.read("mimetype") != b"application/epub+zip":
                print("EPUB has an invalid mimetype")
                return False
    except (OSError, zipfile.BadZipFile, KeyError) as exc:
        print(f"EPUB validation failed: {exc}")
        return False
    return True


def image_to_cover_pdf(image_path: Path, out_pdf: Path) -> bool:
    """Render a cover PNG to a single 6x9 in PDF page at 600 DPI.

    The image is scaled to fit within the 432 x 648 pt page minus a 0.25 in
    white margin on each side, centred on white, so the cover art stays
    inside the page edge (no full-bleed). Returns True on success.
    """
    try:
        from PIL import Image
    except ImportError:
        print("  Pillow not available for cover conversion — skipping covers")
        return False
    try:
        dpi = COVER_DPI  # 600 DPI print cover
        margin_in = 0.25
        margin_px = round(margin_in * dpi)  # 150 px at 600 DPI
        page_w, page_h = TRIM_W_PT, TRIM_H_PT  # 432 x 648 pt (6x9 in)
        img = Image.open(image_path)
        if img.mode not in ("RGB", "L"):
            img = img.convert("RGB")
        iw, ih = img.size
        px_w = round(page_w / 72 * dpi)
        px_h = round(page_h / 72 * dpi)
        # Fit within the page minus the margin on all sides.
        avail_w = px_w - 2 * margin_px
        avail_h = px_h - 2 * margin_px
        scale = min(avail_w / iw, avail_h / ih)
        w = max(1, int(iw * scale))
        h = max(1, int(ih * scale))
        img = img.resize((w, h), Image.LANCZOS)
        canvas = Image.new("RGB", (px_w, px_h), "white")
        canvas.paste(img, ((px_w - w) // 2, (px_h - h) // 2))
        canvas.save(out_pdf, "PDF", resolution=dpi)
        return True
    except Exception as exc:  # noqa: BLE001
        print(f"  Cover conversion failed: {exc} — skipping covers")
        return False


def attach_covers(root: Path, pdf_file: Path) -> Path:
    """Attach the front cover (page 1) at 6x9; the back cover is not embedded.

    The front cover becomes page 1 of the finished book. It is rendered at
    600 DPI on a 6x9 in page. Uses pypdf to merge while preserving the PDF
    outline.
    """
    cover = root / COVER
    back = root / BACK_COVER
    if not cover.exists() and not back.exists():
        print("Cover images not found — skipping cover attach")
        return pdf_file
    try:
        from pypdf import PdfReader, PdfWriter
    except ImportError:
        print("pypdf not installed — skipping cover attach")
        return pdf_file

    build_dir = root / ".build"
    cover_pdf = build_dir / "cover-page.pdf"
    back_pdf = build_dir / "back-cover-page.pdf"
    if cover.exists() and not image_to_cover_pdf(cover, cover_pdf):
        return pdf_file

    writer = PdfWriter()
    try:
        cover_reader = PdfReader(str(cover_pdf)) if cover_pdf.exists() else None
        if cover_reader is not None:
            for page in cover_reader.pages:
                writer.add_page(page)
        book_reader = PdfReader(str(pdf_file))
        writer.append(book_reader)  # keeps the PDF outline intact
        combined = build_dir / "book-with-cover.pdf"
        with open(combined, "wb") as fh:
            writer.write(fh)
        shutil.move(str(combined), str(pdf_file))
        parts = ["front cover"]
        print(f"Attached {' + '.join(parts)} -> {pdf_file.name}")
    finally:
        for tmp in (cover_pdf, back_pdf):
            if tmp.exists():
                tmp.unlink()
    return pdf_file


def build() -> int:
    keep = "--keep-intermediates" in sys.argv
    build_dir = HERE / ".build"
    build_dir.mkdir(exist_ok=True)
    dist = HERE / "dist"
    dist.mkdir(exist_ok=True)

    header = build_dir / "header.tex"
    write_header_tex(header)

    tex = build_dir / "book.tex"
    pdf = build_dir / "book.pdf"
    stamp = datetime.now().strftime("%d %b %Y %H%M")
    final_pdf = dist / f"Fit for HYROX {stamp}.pdf"
    final_epub = dist / f"Fit for HYROX {stamp}.epub"

    sources = FRONT + CHAPTERS + BACK

    # ---- 1. pandoc -> LaTeX (standalone, --toc for engine-generated TOC)
    r = run([
        "pandoc",
        *sources,
        "-s",
        "--top-level-division=chapter",
        "--toc",
        "--toc-depth=2",
        "-H", header,
        "--resource-path", str(HERE),
        "--metadata", f"title={TITLE}",
        "--metadata", f"author={AUTHOR}",
        "-o", tex,
    ])
    if r.returncode != 0:
        print("pandoc failed")
        return 1

    postprocess_tex(tex)

    # ---- 2. pdflatex x2 (x3 if rerun requested)
    passes = 2
    for i in range(1, 4):
        r = run(["pdflatex", "-interaction=nonstopmode", "-halt-on-error",
                 f"-output-directory={build_dir}", "book.tex"],
                cwd=build_dir)
        if r.returncode != 0 and i < passes:
            print(f"pdflatex pass {i} exited {r.returncode} — continuing "
                  "(Unicode warnings are non-fatal)")
        if i >= passes:
            log = (build_dir / "book.log").read_text(encoding="utf-8",
                                                     errors="replace")
            if ("Rerun to get cross-references right" in log
                    or "Label(s) may have changed" in log):
                passes = i + 1
                continue
            break

    if not pdf.exists():
        print("PDF was not produced")
        return 1

    shutil.copyfile(pdf, final_pdf)
    final_pdf = attach_covers(root=HERE, pdf_file=final_pdf)
    if not build_epub(sources=sources, output=final_epub, build_dir=build_dir):
        return 1
    print(f"PDF -> {final_pdf}")
    print(f"EPUB -> {final_epub}")

    # ---- 3. cleanup intermediates (unless asked to keep them)
    if not keep:
        for p in build_dir.iterdir():
            p.unlink()
        build_dir.rmdir()
        for pattern in ("*.aux", "*.log", "*.out", "*.toc", "*.fls",
                        "texput.log"):
            for stray in HERE.glob(pattern):
                stray.unlink()

    return 0


if __name__ == "__main__":
    sys.exit(build())
